//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpClientProgram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class hu_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hu_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcpClientProgram.hu_local", typeof(hu_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tisztít.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csatlakoz.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecsatlakoz.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar.
        /// </summary>
        internal static string hu {
            get {
                return ResourceManager.GetString("hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Élőkép.
        /// </summary>
        internal static string live {
            get {
                return ResourceManager.GetString("live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés adminisztrátorként.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KI.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutató.
        /// </summary>
        internal static string pointer {
            get {
                return ResourceManager.GetString("pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indítsd újra a programot a nyelvváltáshoz.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küldés.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítás.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automata csatlakozás.
        /// </summary>
        internal static string setting_autoconnect {
            get {
                return ResourceManager.GetString("setting_autoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automata feltöltés.
        /// </summary>
        internal static string setting_autoupload {
            get {
                return ResourceManager.GetString("setting_autoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalibrálás.
        /// </summary>
        internal static string setting_calibrate {
            get {
                return ResourceManager.GetString("setting_calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parancs küldés.
        /// </summary>
        internal static string setting_command {
            get {
                return ResourceManager.GetString("setting_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Célszám.
        /// </summary>
        internal static string setting_count {
            get {
                return ResourceManager.GetString("setting_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csatlakozási paraméterek.
        /// </summary>
        internal static string setting_ip {
            get {
                return ResourceManager.GetString("setting_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyelv.
        /// </summary>
        internal static string setting_language {
            get {
                return ResourceManager.GetString("setting_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Címzett lista.
        /// </summary>
        internal static string setting_list {
            get {
                return ResourceManager.GetString("setting_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplófájlok megtekintése.
        /// </summary>
        internal static string setting_log {
            get {
                return ResourceManager.GetString("setting_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időzítő.
        /// </summary>
        internal static string setting_timer {
            get {
                return ResourceManager.GetString("setting_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotóz.
        /// </summary>
        internal static string shoot {
            get {
                return ResourceManager.GetString("shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบไทย.
        /// </summary>
        internal static string th {
            get {
                return ResourceManager.GetString("th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalog.
        /// </summary>
        internal static string tl {
            get {
                return ResourceManager.GetString("tl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltöltés.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
    }
}
