//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpClientProgram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tl_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tl_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcpClientProgram.tl_local", typeof(tl_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaliwalas.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kumonekta.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiskonekta.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar.
        /// </summary>
        internal static string hu {
            get {
                return ResourceManager.GetString("hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live na larawan.
        /// </summary>
        internal static string live {
            get {
                return ResourceManager.GetString("live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag-login bilang admin.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAKA-OFF.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAKA-ON.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        internal static string pointer {
            get {
                return ResourceManager.GetString("pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-restart ang program para maglapat ng mga pagbabago.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ipadala.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itakda.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoconnect.
        /// </summary>
        internal static string setting_autoconnect {
            get {
                return ResourceManager.GetString("setting_autoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoupload.
        /// </summary>
        internal static string setting_autoupload {
            get {
                return ResourceManager.GetString("setting_autoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag-calibrate.
        /// </summary>
        internal static string setting_calibrate {
            get {
                return ResourceManager.GetString("setting_calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direktang utos.
        /// </summary>
        internal static string setting_command {
            get {
                return ResourceManager.GetString("setting_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilang ng pag-scan.
        /// </summary>
        internal static string setting_count {
            get {
                return ResourceManager.GetString("setting_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mga parameter ng koneksyon.
        /// </summary>
        internal static string setting_ip {
            get {
                return ResourceManager.GetString("setting_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wika.
        /// </summary>
        internal static string setting_language {
            get {
                return ResourceManager.GetString("setting_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listahan ng address.
        /// </summary>
        internal static string setting_list {
            get {
                return ResourceManager.GetString("setting_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buksan ang direktoryo ng log.
        /// </summary>
        internal static string setting_log {
            get {
                return ResourceManager.GetString("setting_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string setting_timer {
            get {
                return ResourceManager.GetString("setting_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mga setting.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot.
        /// </summary>
        internal static string shoot {
            get {
                return ResourceManager.GetString("shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แบบไทย.
        /// </summary>
        internal static string th {
            get {
                return ResourceManager.GetString("th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalog.
        /// </summary>
        internal static string tl {
            get {
                return ResourceManager.GetString("tl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag-upload.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
    }
}
